/**
* Copyright 2015 Inpher, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package utils;

import java.util.HashMap;
import java.util.Map;

public class ServiceTestResult {
	private ServiceTestStatus status;
	private String statusMessage;
	private Exception exception;
	private Map<String, Object> data;
	
	public static ServiceTestResult createSuccess(String message) {
		return new ServiceTestResult(ServiceTestStatus.OK,message,null);
	}
	public static ServiceTestResult createSuccess() {
		return createSuccess("Success!");
	}
	public static ServiceTestResult createFailure(ServiceTestStatus status,  String errorMessage, Exception  e) {
		return new ServiceTestResult(status,errorMessage,e);
	}
	public static ServiceTestResult createFailure(ServiceTestStatus status, String errorMessage) {
		return createFailure(status,errorMessage,null);
	}
	public static ServiceTestResult createFailure(ServiceTestStatus status,Exception e) {
		return createFailure(status,"Failed: "+e.getMessage(),e);
	}
	
	//autogenerated
	
	public ServiceTestStatus getStatus() {
		return status;
	}
	public void setStatus(ServiceTestStatus status) {
		this.status = status;
	}
	public void setData(String key, Object value) {
		this.data.put(key, value);
	}
	public Object getData(String key) {
		return this.data.get(key);
	}
	@SuppressWarnings("unchecked")
	public <T> T getData(String key, Class<T> castType) {
		return (T) this.data.get(key);
	}
	public String getStatusMessage() {
		return statusMessage;
	}
	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}
	public Exception getException() {
		return exception;
	}
	public void setException(Exception exception) {
		this.exception = exception;
	}
	public ServiceTestResult() {
	}
	public ServiceTestResult(ServiceTestStatus status, String statusMessage, Exception exception) {
		super();
		this.status = status;
		this.statusMessage = statusMessage;
		this.exception = exception;
		this.data=new HashMap<>();
	}
	
	public String toString() {
		if (status==ServiceTestStatus.OK) return "OK: "+statusMessage;
		if (exception!=null) exception.printStackTrace();
		return status+"\n"+statusMessage;
	}
}
